## KEYBINDS

unbind C-b

# Set the new prefix to Ctrl-a
set -g prefix C-a

# Reload config
bind r source-file ~/.tmux-amy

# Switch panes
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Split panes
bind \\ split-window -h
bind - split-window -v

# Enable mouse mode
set -g mouse on

# Faster command sequences
set -s escape-time 10


# APPEARANCE
set -ga terminal-overrides ",xterm-256color:Tc"

set -g default-terminal "tmux-256color"
set -g visual-activity off
#set -g visual-bell off
#set -g visual-silence off
setw -g monitor-activity on
#set -g bell-action none

set -g set-titles on
setw -g automatic-rename on
set -g renumber-windows on

# Modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# Panel borders
set -g pane-active-border-style 'fg=orange bg=default'
set -g pane-border-style 'fg=gray bg=default'

# Status Bar
set -g status-position bottom
set -g status-interval 4
set -g status-left '#[fg=black,bg=yellow][ #S ]'
set -g status-right ''
set -g status-justify centre
set -g status-style 'bg=default fg=default'

# Window
setw -g window-status-style 'fg=white bg=default'
setw -g window-status-current-style 'fg=default bg=default'
setw -g window-status-format '#[bg=black]#[fg=black,bold] #I #[bg=default] #[fg=black]#W  '
setw -g window-status-current-format '#[fg=white]#[bg=cyan] #I #[fg=cyan]#[bg=default] #W  '

# Messages
set -g message-style 'fg=default bg=default bold'
